//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/message.proto
namespace SSIT.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"MessageID")]
    public enum MessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginModel", Value=0)]
      LoginModel = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSLogin", Value=1)]
      CSLogin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCLoginResult", Value=2)]
      SCLoginResult = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSLogout", Value=3)]
      CSLogout = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCLogoutResult", Value=4)]
      SCLogoutResult = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCFeedBackSaveResult", Value=5)]
      SCFeedBackSaveResult = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SystemModel", Value=1000)]
      SystemModel = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCOrganizeInfoListResult", Value=1001)]
      SCOrganizeInfoListResult = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveOrganizeInfoResult", Value=1002)]
      SCSaveOrganizeInfoResult = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteOrganizeInfoResult", Value=1003)]
      SCDeleteOrganizeInfoResult = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCUserInfoListResult", Value=1004)]
      SCUserInfoListResult = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveUserInfoResult", Value=1005)]
      SCSaveUserInfoResult = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteUserInfoResult", Value=1006)]
      SCDeleteUserInfoResult = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCAuthorityListResult", Value=1007)]
      SCAuthorityListResult = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCLogInfoListResult", Value=1008)]
      SCLogInfoListResult = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteLogInfoResult", Value=1009)]
      SCDeleteLogInfoResult = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneModel", Value=2000)]
      SceneModel = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCCompanyInfoListResult", Value=2001)]
      SCCompanyInfoListResult = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveCompanyInfoResult", Value=2002)]
      SCSaveCompanyInfoResult = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteCompanyInfoResult", Value=2003)]
      SCDeleteCompanyInfoResult = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCIndustryInfoListResult", Value=2004)]
      SCIndustryInfoListResult = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveIndustryInfoResult", Value=2005)]
      SCSaveIndustryInfoResult = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteIndustryInfoResult", Value=2006)]
      SCDeleteIndustryInfoResult = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveDeviceInfoResult", Value=2007)]
      SCSaveDeviceInfoResult = 2007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeviceBaseInfolistResult", Value=2008)]
      SCDeviceBaseInfolistResult = 2008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveSceneInfoResult", Value=2009)]
      SCSaveSceneInfoResult = 2009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSceneInfoListResult", Value=2010)]
      SCSceneInfoListResult = 2010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteSceneInfoResult", Value=2011)]
      SCDeleteSceneInfoResult = 2011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSwitchDeviceInfolistResult", Value=2012)]
      SCSwitchDeviceInfolistResult = 2012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveSwitchDeviceInfoResult", Value=2013)]
      SCSaveSwitchDeviceInfoResult = 2013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteSwitchDeviceInfoResult", Value=2014)]
      SCDeleteSwitchDeviceInfoResult = 2014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCBundingSwitchDeviceResult", Value=2015)]
      SCBundingSwitchDeviceResult = 2015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCRemoveBundingSwitchDeviceResult", Value=2016)]
      SCRemoveBundingSwitchDeviceResult = 2016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeviceTypelistResult", Value=2017)]
      SCDeviceTypelistResult = 2017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveDeviceTypeResult", Value=2018)]
      SCSaveDeviceTypeResult = 2018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteDeviceTypeResult", Value=2019)]
      SCDeleteDeviceTypeResult = 2019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteDeviceBaseInfoResult", Value=2020)]
      SCDeleteDeviceBaseInfoResult = 2020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSwitchDeviceTypeInfolistResult", Value=2021)]
      SCSwitchDeviceTypeInfolistResult = 2021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveSwitchDeviceTypeResult", Value=2022)]
      SCSaveSwitchDeviceTypeResult = 2022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteSwitchDeviceTypeResult", Value=2023)]
      SCDeleteSwitchDeviceTypeResult = 2023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AccidentModel", Value=3000)]
      AccidentModel = 3000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveMeasureTypeResult", Value=3001)]
      SCSaveMeasureTypeResult = 3001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteMeasureTypeResult", Value=3002)]
      SCDeleteMeasureTypeResult = 3002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCMeasureTypelistResult", Value=3003)]
      SCMeasureTypelistResult = 3003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCMeasureInfoListResult", Value=3004)]
      SCMeasureInfoListResult = 3004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveMeasureResult", Value=3005)]
      SCSaveMeasureResult = 3005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteMeasureResult", Value=3006)]
      SCDeleteMeasureResult = 3006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCTaskTypeListResult", Value=3007)]
      SCTaskTypeListResult = 3007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveTaskTypeResult", Value=3008)]
      SCSaveTaskTypeResult = 3008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteTaskTypeResult", Value=3009)]
      SCDeleteTaskTypeResult = 3009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveTaskInfoResult", Value=3010)]
      SCSaveTaskInfoResult = 3010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteTaskInfoResult", Value=3011)]
      SCDeleteTaskInfoResult = 3011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCTaskInfoListResult", Value=3012)]
      SCTaskInfoListResult = 3012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCAccidentListResult", Value=3015)]
      SCAccidentListResult = 3015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSAddAccident", Value=3016)]
      CSAddAccident = 3016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCAddAccidentResult", Value=3017)]
      SCAddAccidentResult = 3017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteAccidentResult", Value=3018)]
      SCDeleteAccidentResult = 3018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSUpdateAccident", Value=3019)]
      CSUpdateAccident = 3019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCUpdateAccidentResult", Value=3020)]
      SCUpdateAccidentResult = 3020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCAccidentTypeListResult", Value=3021)]
      SCAccidentTypeListResult = 3021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCCharactorTypeListResult", Value=3022)]
      SCCharactorTypeListResult = 3022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveCharactorTypeResult", Value=3023)]
      SCSaveCharactorTypeResult = 3023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteCharactorTypeResult", Value=3024)]
      SCDeleteCharactorTypeResult = 3024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCCharacterListResult", Value=3025)]
      SCCharacterListResult = 3025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveCharactorInfoResult", Value=3026)]
      SCSaveCharactorInfoResult = 3026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteCharactorInfoResult", Value=3027)]
      SCDeleteCharactorInfoResult = 3027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSAddGroupInfo", Value=3028)]
      CSAddGroupInfo = 3028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCAddGroupInfoResult", Value=3029)]
      SCAddGroupInfoResult = 3029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteGroupInfoResult", Value=3030)]
      SCDeleteGroupInfoResult = 3030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSUpdateGroupInfo", Value=3031)]
      CSUpdateGroupInfo = 3031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCUpdateGroupInfoResult", Value=3032)]
      SCUpdateGroupInfoResult = 3032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCGroupInfoListResult", Value=3033)]
      SCGroupInfoListResult = 3033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCEvaluationInfoListResult", Value=3034)]
      SCEvaluationInfoListResult = 3034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSaveEvaluationInfoResult", Value=3035)]
      SCSaveEvaluationInfoResult = 3035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCDeleteEvaluationInfoResult", Value=3036)]
      SCDeleteEvaluationInfoResult = 3036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSSceneEditLockStatList", Value=3037)]
      CSSceneEditLockStatList = 3037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSceneEditLockStatListResult", Value=3038)]
      SCSceneEditLockStatListResult = 3038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSSchemeEditLockStatList", Value=3039)]
      CSSchemeEditLockStatList = 3039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCSchemeEditLockStatListResult", Value=3040)]
      SCSchemeEditLockStatListResult = 3040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSUpdateEditLockStat", Value=3041)]
      CSUpdateEditLockStat = 3041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCUpdateEditLockStatListResult", Value=3042)]
      SCUpdateEditLockStatListResult = 3042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSDeleteCharactorType", Value=3043)]
      CSDeleteCharactorType = 3043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CommenModel", Value=9000)]
      CommenModel = 9000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSCommonQuery", Value=9001)]
      CSCommonQuery = 9001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSCommonSave", Value=9002)]
      CSCommonSave = 9002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSCommonRemove", Value=9003)]
      CSCommonRemove = 9003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCCommonResult", Value=9004)]
      SCCommonResult = 9004
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"QueryKey")]
    public enum QueryKey
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"sallOrganizeInfoList", Value=0)]
      sallOrganizeInfoList = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"userInfoList", Value=1)]
      userInfoList = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"powerList", Value=2)]
      powerList = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"logInfoList", Value=3)]
      logInfoList = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"companyList", Value=4)]
      companyList = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"industryInfoList", Value=5)]
      industryInfoList = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"deviceList", Value=6)]
      deviceList = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"sceneMgrInfoList", Value=7)]
      sceneMgrInfoList = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"switchDeviceList", Value=8)]
      switchDeviceList = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"switchDeviceTypeList", Value=9)]
      switchDeviceTypeList = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"switchBundingList", Value=10)]
      switchBundingList = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"deviceTypeList", Value=11)]
      deviceTypeList = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"skillTypeList", Value=12)]
      skillTypeList = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"skillList", Value=13)]
      skillList = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"taskTypeList", Value=14)]
      taskTypeList = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"taskInfoList", Value=15)]
      taskInfoList = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"accidentInfoList", Value=16)]
      accidentInfoList = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"accidentTypeList", Value=17)]
      accidentTypeList = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"charactorTypeList", Value=18)]
      charactorTypeList = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"charactorInfoList", Value=19)]
      charactorInfoList = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"evaluationList", Value=20)]
      evaluationList = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"groupInfoList", Value=21)]
      groupInfoList = 21
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SaveTarget")]
    public enum SaveTarget
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"organization", Value=0)]
      organization = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"user", Value=1)]
      user = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"log", Value=2)]
      log = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"feed_back", Value=3)]
      feed_back = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"company", Value=4)]
      company = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"industry", Value=5)]
      industry = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"deviceinfo", Value=6)]
      deviceinfo = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillscene", Value=7)]
      drillscene = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"switchdevice", Value=8)]
      switchdevice = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"switchdeviceagent", Value=9)]
      switchdeviceagent = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"devicetype", Value=10)]
      devicetype = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillskilltype", Value=11)]
      drillskilltype = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillskill", Value=12)]
      drillskill = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillmissiontype", Value=13)]
      drillmissiontype = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillmission", Value=14)]
      drillmission = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillmissionpoolagent", Value=15)]
      drillmissionpoolagent = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"switchdevicetype", Value=16)]
      switchdevicetype = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillscheme", Value=17)]
      drillscheme = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillcharactertype", Value=18)]
      drillcharactertype = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillcharacter", Value=19)]
      drillcharacter = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillgroup", Value=20)]
      drillgroup = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"drillevaluate", Value=21)]
      drillevaluate = 21
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SysErrorCode")]
    public enum SysErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Success", Value=0)]
      Success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CodeError", Value=1)]
      CodeError = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DataBaseError", Value=2)]
      DataBaseError = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogicError", Value=3)]
      LogicError = 3
    }
  
}