//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/unetmgr.proto
namespace SSIT.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSSWarpMembersRequest")]
  public partial class CSSWarpMembersRequest : global::ProtoBuf.IExtensible
  {
    public CSSWarpMembersRequest() {}
    
    private SSIT.proto.SwarpMemberInfo _swarpInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"swarpInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.SwarpMemberInfo swarpInfo
    {
      get { return _swarpInfo; }
      set { _swarpInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCSWarpMembersResult")]
  public partial class SCSWarpMembersResult : global::ProtoBuf.IExtensible
  {
    public SCSWarpMembersResult() {}
    
    private SSIT.proto.SwarpMemberInfo _swarpInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"swarpInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.SwarpMemberInfo swarpInfo
    {
      get { return _swarpInfo; }
      set { _swarpInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCMembersResult")]
  public partial class SCMembersResult : global::ProtoBuf.IExtensible
  {
    public SCMembersResult() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.MemberInfo> _memberList = new global::System.Collections.Generic.List<SSIT.proto.MemberInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"memberList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.MemberInfo> memberList
    {
      get { return _memberList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSSpawnSceneObjectRequest")]
  public partial class CSSpawnSceneObjectRequest : global::ProtoBuf.IExtensible
  {
    public CSSpawnSceneObjectRequest() {}
    
    private SSIT.proto.SpawnSceneObjectInfo _spawnInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"spawnInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.SpawnSceneObjectInfo spawnInfo
    {
      get { return _spawnInfo; }
      set { _spawnInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCSpawnSceneObjectResult")]
  public partial class SCSpawnSceneObjectResult : global::ProtoBuf.IExtensible
  {
    public SCSpawnSceneObjectResult() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private SSIT.proto.SpawnSceneObjectInfo _spawnInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"spawnInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.SpawnSceneObjectInfo spawnInfo
    {
      get { return _spawnInfo; }
      set { _spawnInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSDestorySceneObjectRequest")]
  public partial class CSDestorySceneObjectRequest : global::ProtoBuf.IExtensible
  {
    public CSDestorySceneObjectRequest() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private uint _netId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"netId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint netId
    {
      get { return _netId; }
      set { _netId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCDestorySceneObjectResult")]
  public partial class SCDestorySceneObjectResult : global::ProtoBuf.IExtensible
  {
    public SCDestorySceneObjectResult() {}
    
    private int _netId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"netId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int netId
    {
      get { return _netId; }
      set { _netId = value; }
    }
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSSyncTransRequest")]
  public partial class CSSyncTransRequest : global::ProtoBuf.IExtensible
  {
    public CSSyncTransRequest() {}
    
    private SSIT.proto.TransTempInfo _transInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"transInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.TransTempInfo transInfo
    {
      get { return _transInfo; }
      set { _transInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCSyncTransResult")]
  public partial class SCSyncTransResult : global::ProtoBuf.IExtensible
  {
    public SCSyncTransResult() {}
    
    private SSIT.proto.TransTempInfo _transInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"transInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.TransTempInfo transInfo
    {
      get { return _transInfo; }
      set { _transInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSAttachRequest")]
  public partial class CSAttachRequest : global::ProtoBuf.IExtensible
  {
    public CSAttachRequest() {}
    
    private SSIT.proto.AttachObjectInfo _attachInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attachInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.AttachObjectInfo attachInfo
    {
      get { return _attachInfo; }
      set { _attachInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCAttachResult")]
  public partial class SCAttachResult : global::ProtoBuf.IExtensible
  {
    public SCAttachResult() {}
    
    private SSIT.proto.AttachObjectInfo _attachInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attachInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.AttachObjectInfo attachInfo
    {
      get { return _attachInfo; }
      set { _attachInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSChatMessageRequest")]
  public partial class CSChatMessageRequest : global::ProtoBuf.IExtensible
  {
    public CSChatMessageRequest() {}
    
    private SSIT.proto.MessageInfo _attachInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attachInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.MessageInfo attachInfo
    {
      get { return _attachInfo; }
      set { _attachInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCChatMessageResult")]
  public partial class SCChatMessageResult : global::ProtoBuf.IExtensible
  {
    public SCChatMessageResult() {}
    
    private SSIT.proto.MessageInfo _attachInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attachInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.MessageInfo attachInfo
    {
      get { return _attachInfo; }
      set { _attachInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSCommandRequest")]
  public partial class CSCommandRequest : global::ProtoBuf.IExtensible
  {
    public CSCommandRequest() {}
    
    private SSIT.proto.CommandInfo _command = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.CommandInfo command
    {
      get { return _command; }
      set { _command = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCCommandResult")]
  public partial class SCCommandResult : global::ProtoBuf.IExtensible
  {
    public SCCommandResult() {}
    
    private SSIT.proto.CommandInfo _command = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.CommandInfo command
    {
      get { return _command; }
      set { _command = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSCountPresonRequest")]
  public partial class CSCountPresonRequest : global::ProtoBuf.IExtensible
  {
    public CSCountPresonRequest() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.PersonnelCountInfo> _countInfo = new global::System.Collections.Generic.List<SSIT.proto.PersonnelCountInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"countInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.PersonnelCountInfo> countInfo
    {
      get { return _countInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCCountPresonResult")]
  public partial class SCCountPresonResult : global::ProtoBuf.IExtensible
  {
    public SCCountPresonResult() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.PersonnelCountInfo> _countInfo = new global::System.Collections.Generic.List<SSIT.proto.PersonnelCountInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"countInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.PersonnelCountInfo> countInfo
    {
      get { return _countInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSInteractionRequest")]
  public partial class CSInteractionRequest : global::ProtoBuf.IExtensible
  {
    public CSInteractionRequest() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.InteractionInfo> _interactionInfo = new global::System.Collections.Generic.List<SSIT.proto.InteractionInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"interactionInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.InteractionInfo> interactionInfo
    {
      get { return _interactionInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCInteractionResult")]
  public partial class SCInteractionResult : global::ProtoBuf.IExtensible
  {
    public SCInteractionResult() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.InteractionInfo> _interactionInfo = new global::System.Collections.Generic.List<SSIT.proto.InteractionInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"interactionInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.InteractionInfo> interactionInfo
    {
      get { return _interactionInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSEnvironmentRequest")]
  public partial class CSEnvironmentRequest : global::ProtoBuf.IExtensible
  {
    public CSEnvironmentRequest() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.EnvironmentInfo> _enviInfo = new global::System.Collections.Generic.List<SSIT.proto.EnvironmentInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"enviInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.EnvironmentInfo> enviInfo
    {
      get { return _enviInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCEnvironmentResult")]
  public partial class SCEnvironmentResult : global::ProtoBuf.IExtensible
  {
    public SCEnvironmentResult() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.EnvironmentInfo> _enviInfo = new global::System.Collections.Generic.List<SSIT.proto.EnvironmentInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"enviInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.EnvironmentInfo> enviInfo
    {
      get { return _enviInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSRoutePlanRequest")]
  public partial class CSRoutePlanRequest : global::ProtoBuf.IExtensible
  {
    public CSRoutePlanRequest() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.RoutePlanInfo> _routeInfo = new global::System.Collections.Generic.List<SSIT.proto.RoutePlanInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"routeInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.RoutePlanInfo> routeInfo
    {
      get { return _routeInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSRoutePlanResult")]
  public partial class CSRoutePlanResult : global::ProtoBuf.IExtensible
  {
    public CSRoutePlanResult() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.RoutePlanInfo> _routeInfo = new global::System.Collections.Generic.List<SSIT.proto.RoutePlanInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"routeInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.RoutePlanInfo> routeInfo
    {
      get { return _routeInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPopTipRequest")]
  public partial class CSPopTipRequest : global::ProtoBuf.IExtensible
  {
    public CSPopTipRequest() {}
    
    private SSIT.proto.MessageInfo _popInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"popInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.MessageInfo popInfo
    {
      get { return _popInfo; }
      set { _popInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCPopTipResult")]
  public partial class SCPopTipResult : global::ProtoBuf.IExtensible
  {
    public SCPopTipResult() {}
    
    private SSIT.proto.MessageInfo _popInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"popInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.MessageInfo popInfo
    {
      get { return _popInfo; }
      set { _popInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSFollowClientRequest")]
  public partial class CSFollowClientRequest : global::ProtoBuf.IExtensible
  {
    public CSFollowClientRequest() {}
    
    private string _userID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }
    private int _isFollow = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isFollow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isFollow
    {
      get { return _isFollow; }
      set { _isFollow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCFollowClientResult")]
  public partial class SCFollowClientResult : global::ProtoBuf.IExtensible
  {
    public SCFollowClientResult() {}
    
    private string _userID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }
    private int _isFollow = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isFollow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isFollow
    {
      get { return _isFollow; }
      set { _isFollow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSSyncPlayerInfoRequest")]
  public partial class CSSyncPlayerInfoRequest : global::ProtoBuf.IExtensible
  {
    public CSSyncPlayerInfoRequest() {}
    
    private SSIT.proto.PlayerInfo _playerInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PlayerInfo playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCSyncPlayerInfoResult")]
  public partial class SCSyncPlayerInfoResult : global::ProtoBuf.IExtensible
  {
    public SCSyncPlayerInfoResult() {}
    
    private SSIT.proto.PlayerInfo _playerInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PlayerInfo playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSSyncSceneObjInfoRequest")]
  public partial class CSSyncSceneObjInfoRequest : global::ProtoBuf.IExtensible
  {
    public CSSyncSceneObjInfoRequest() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.SyncSceneObjInfo> _sceneObjInfo = new global::System.Collections.Generic.List<SSIT.proto.SyncSceneObjInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"sceneObjInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.SyncSceneObjInfo> sceneObjInfo
    {
      get { return _sceneObjInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCSyncSceneObjInfoResult")]
  public partial class SCSyncSceneObjInfoResult : global::ProtoBuf.IExtensible
  {
    public SCSyncSceneObjInfoResult() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.SyncSceneObjInfo> _sceneObjInfo = new global::System.Collections.Generic.List<SSIT.proto.SyncSceneObjInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"sceneObjInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.SyncSceneObjInfo> sceneObjInfo
    {
      get { return _sceneObjInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSStartDrillRequest")]
  public partial class CSStartDrillRequest : global::ProtoBuf.IExtensible
  {
    public CSStartDrillRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStartDrillResult")]
  public partial class SCStartDrillResult : global::ProtoBuf.IExtensible
  {
    public SCStartDrillResult() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSEndDrillRequest")]
  public partial class CSEndDrillRequest : global::ProtoBuf.IExtensible
  {
    public CSEndDrillRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCEndDrillResult")]
  public partial class SCEndDrillResult : global::ProtoBuf.IExtensible
  {
    public SCEndDrillResult() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSEvacuateRequest")]
  public partial class CSEvacuateRequest : global::ProtoBuf.IExtensible
  {
    public CSEvacuateRequest() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.EvacuateInfo> _evacuateInfo = new global::System.Collections.Generic.List<SSIT.proto.EvacuateInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"evacuateInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.EvacuateInfo> evacuateInfo
    {
      get { return _evacuateInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCEvacuateResult")]
  public partial class SCEvacuateResult : global::ProtoBuf.IExtensible
  {
    public SCEvacuateResult() {}
    
    private readonly global::System.Collections.Generic.List<SSIT.proto.EvacuateInfo> _evacuateInfo = new global::System.Collections.Generic.List<SSIT.proto.EvacuateInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"evacuateInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.EvacuateInfo> evacuateInfo
    {
      get { return _evacuateInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoadSceneRequest")]
  public partial class CSLoadSceneRequest : global::ProtoBuf.IExtensible
  {
    public CSLoadSceneRequest() {}
    
    private SSIT.proto.LevelInfo _levelInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"levelInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.LevelInfo levelInfo
    {
      get { return _levelInfo; }
      set { _levelInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCLoadSceneResult")]
  public partial class SCLoadSceneResult : global::ProtoBuf.IExtensible
  {
    public SCLoadSceneResult() {}
    
    private SSIT.proto.LevelInfo _levelInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"levelInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.LevelInfo levelInfo
    {
      get { return _levelInfo; }
      set { _levelInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoadSceneProcessRequest")]
  public partial class CSLoadSceneProcessRequest : global::ProtoBuf.IExtensible
  {
    public CSLoadSceneProcessRequest() {}
    
    private string _userId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private float _readyTime = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"readyTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float readyTime
    {
      get { return _readyTime; }
      set { _readyTime = value; }
    }
    private int _readyState = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"readyState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int readyState
    {
      get { return _readyState; }
      set { _readyState = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCLoadSceneProcessResult")]
  public partial class SCLoadSceneProcessResult : global::ProtoBuf.IExtensible
  {
    public SCLoadSceneProcessResult() {}
    
    private string _userId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private float _readyTime = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"readyTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float readyTime
    {
      get { return _readyTime; }
      set { _readyTime = value; }
    }
    private int _readyState = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"readyState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int readyState
    {
      get { return _readyState; }
      set { _readyState = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSAssignClientAuthorityRequest")]
  public partial class CSAssignClientAuthorityRequest : global::ProtoBuf.IExtensible
  {
    public CSAssignClientAuthorityRequest() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _netId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"netId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int netId
    {
      get { return _netId; }
      set { _netId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCAssignClientAuthorityResult")]
  public partial class SCAssignClientAuthorityResult : global::ProtoBuf.IExtensible
  {
    public SCAssignClientAuthorityResult() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLobbyChatMessageRequest")]
  public partial class CSLobbyChatMessageRequest : global::ProtoBuf.IExtensible
  {
    public CSLobbyChatMessageRequest() {}
    
    private SSIT.proto.LobbyChatMessage _Message = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.LobbyChatMessage Message
    {
      get { return _Message; }
      set { _Message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCLobbyChatMessageResult")]
  public partial class SCLobbyChatMessageResult : global::ProtoBuf.IExtensible
  {
    public SCLobbyChatMessageResult() {}
    
    private SSIT.proto.LobbyChatMessage _Message = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.LobbyChatMessage Message
    {
      get { return _Message; }
      set { _Message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LevelInfo")]
  public partial class LevelInfo : global::ProtoBuf.IExtensible
  {
    public LevelInfo() {}
    
    private int _sceneId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private string _sceneName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sceneName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sceneName
    {
      get { return _sceneName; }
      set { _sceneName = value; }
    }
    private int _sceneMode = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sceneMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sceneMode
    {
      get { return _sceneMode; }
      set { _sceneMode = value; }
    }
    private int _physicsMode = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"physicsMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int physicsMode
    {
      get { return _physicsMode; }
      set { _physicsMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemberInfo")]
  public partial class MemberInfo : global::ProtoBuf.IExtensible
  {
    public MemberInfo() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _userID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private int _connId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"connId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int connId
    {
      get { return _connId; }
      set { _connId = value; }
    }
    private int _ready = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private int _empty = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"empty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int empty
    {
      get { return _empty; }
      set { _empty = value; }
    }
    private string _groupID = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"groupID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string groupID
    {
      get { return _groupID; }
      set { _groupID = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwarpMemberInfo")]
  public partial class SwarpMemberInfo : global::ProtoBuf.IExtensible
  {
    public SwarpMemberInfo() {}
    
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private SSIT.proto.MemberInfo _curInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"curInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.MemberInfo curInfo
    {
      get { return _curInfo; }
      set { _curInfo = value; }
    }
    private SSIT.proto.MemberInfo _tarInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tarInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.MemberInfo tarInfo
    {
      get { return _tarInfo; }
      set { _tarInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttachObjectInfo")]
  public partial class AttachObjectInfo : global::ProtoBuf.IExtensible
  {
    public AttachObjectInfo() {}
    
    private string _ownerGuid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ownerGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ownerGuid
    {
      get { return _ownerGuid; }
      set { _ownerGuid = value; }
    }
    private string _attachGuid = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attachGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string attachGuid
    {
      get { return _attachGuid; }
      set { _attachGuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransTempInfo")]
  public partial class TransTempInfo : global::ProtoBuf.IExtensible
  {
    public TransTempInfo() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private SSIT.proto.PBVector3 _position = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PBVector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private SSIT.proto.PBQuaternion _rotation = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PBQuaternion rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private SSIT.proto.PBVector3 _scale = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PBVector3 scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private float _tamp = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float tamp
    {
      get { return _tamp; }
      set { _tamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnSceneObjectInfo")]
  public partial class SpawnSceneObjectInfo : global::ProtoBuf.IExtensible
  {
    public SpawnSceneObjectInfo() {}
    
    private int _dataId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dataId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dataId
    {
      get { return _dataId; }
      set { _dataId = value; }
    }
    private int _netId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"netId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int netId
    {
      get { return _netId; }
      set { _netId = value; }
    }
    private SSIT.proto.PBVector3 _position = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PBVector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private SSIT.proto.PBQuaternion _rotation = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PBQuaternion rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private SSIT.proto.PBVector3 _scale = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PBVector3 scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private string _groupId = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageInfo")]
  public partial class MessageInfo : global::ProtoBuf.IExtensible
  {
    public MessageInfo() {}
    
    private SSIT.proto.EnMessageType _MessageType = SSIT.proto.EnMessageType.ACTION;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MessageType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SSIT.proto.EnMessageType.ACTION)]
    public SSIT.proto.EnMessageType MessageType
    {
      get { return _MessageType; }
      set { _MessageType = value; }
    }
    private string _groupName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"groupName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string groupName
    {
      get { return _groupName; }
      set { _groupName = value; }
    }
    private string _userDisplayName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userDisplayName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userDisplayName
    {
      get { return _userDisplayName; }
      set { _userDisplayName = value; }
    }
    private string _time = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string time
    {
      get { return _time; }
      set { _time = value; }
    }
    private string _messageContent = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"messageContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string messageContent
    {
      get { return _messageContent; }
      set { _messageContent = value; }
    }
    private string _messageHighlightContent = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"messageHighlightContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string messageHighlightContent
    {
      get { return _messageHighlightContent; }
      set { _messageHighlightContent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommandInfo")]
  public partial class CommandInfo : global::ProtoBuf.IExtensible
  {
    public CommandInfo() {}
    
    private string _msgId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    private string _param = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param
    {
      get { return _param; }
      set { _param = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PersonnelCountInfo")]
  public partial class PersonnelCountInfo : global::ProtoBuf.IExtensible
  {
    public PersonnelCountInfo() {}
    
    private string _DisplayName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"DisplayName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DisplayName
    {
      get { return _DisplayName; }
      set { _DisplayName = value; }
    }
    private string _Data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private bool _IsArrived = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"IsArrived", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsArrived
    {
      get { return _IsArrived; }
      set { _IsArrived = value; }
    }
    private bool _IsCommunicated = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"IsCommunicated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsCommunicated
    {
      get { return _IsCommunicated; }
      set { _IsCommunicated = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InteractionInfo")]
  public partial class InteractionInfo : global::ProtoBuf.IExtensible
  {
    public InteractionInfo() {}
    
    private string _interactionPlayer = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"interactionPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string interactionPlayer
    {
      get { return _interactionPlayer; }
      set { _interactionPlayer = value; }
    }
    private string _interactionObject = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"interactionObject", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string interactionObject
    {
      get { return _interactionObject; }
      set { _interactionObject = value; }
    }
    private int _interactionState = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"interactionState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int interactionState
    {
      get { return _interactionState; }
      set { _interactionState = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnvironmentInfo")]
  public partial class EnvironmentInfo : global::ProtoBuf.IExtensible
  {
    public EnvironmentInfo() {}
    
    private SSIT.proto.EnWeather _Weather = SSIT.proto.EnWeather.SUN;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Weather", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SSIT.proto.EnWeather.SUN)]
    public SSIT.proto.EnWeather Weather
    {
      get { return _Weather; }
      set { _Weather = value; }
    }
    private SSIT.proto.EnWindDirection _WindDirection = SSIT.proto.EnWindDirection.NOWIND;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"WindDirection", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SSIT.proto.EnWindDirection.NOWIND)]
    public SSIT.proto.EnWindDirection WindDirection
    {
      get { return _WindDirection; }
      set { _WindDirection = value; }
    }
    private int _WindLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"WindLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int WindLevel
    {
      get { return _WindLevel; }
      set { _WindLevel = value; }
    }
    private float _WindVelocity = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"WindVelocity", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float WindVelocity
    {
      get { return _WindVelocity; }
      set { _WindVelocity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoutePlanInfo")]
  public partial class RoutePlanInfo : global::ProtoBuf.IExtensible
  {
    public RoutePlanInfo() {}
    
    private int _PathType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PathType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PathType
    {
      get { return _PathType; }
      set { _PathType = value; }
    }
    private string _PathName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PathName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PathName
    {
      get { return _PathName; }
      set { _PathName = value; }
    }
    private readonly global::System.Collections.Generic.List<SSIT.proto.PBVector3> _Vertexes = new global::System.Collections.Generic.List<SSIT.proto.PBVector3>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Vertexes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.PBVector3> Vertexes
    {
      get { return _Vertexes; }
    }
  
    private bool _enable = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enable
    {
      get { return _enable; }
      set { _enable = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private readonly global::System.Collections.Generic.List<SSIT.proto.SyncVar> _vars = new global::System.Collections.Generic.List<SSIT.proto.SyncVar>();
    [global::ProtoBuf.ProtoMember(3, Name=@"vars", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.SyncVar> vars
    {
      get { return _vars; }
    }
  
    private readonly global::System.Collections.Generic.List<SSIT.proto.EquipInfo> _equips = new global::System.Collections.Generic.List<SSIT.proto.EquipInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.EquipInfo> equips
    {
      get { return _equips; }
    }
  
    private readonly global::System.Collections.Generic.List<SSIT.proto.EquipInfo> _userEquips = new global::System.Collections.Generic.List<SSIT.proto.EquipInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"userEquips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.EquipInfo> userEquips
    {
      get { return _userEquips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncSceneObjInfo")]
  public partial class SyncSceneObjInfo : global::ProtoBuf.IExtensible
  {
    public SyncSceneObjInfo() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private readonly global::System.Collections.Generic.List<SSIT.proto.SyncVar> _vars = new global::System.Collections.Generic.List<SSIT.proto.SyncVar>();
    [global::ProtoBuf.ProtoMember(2, Name=@"vars", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SSIT.proto.SyncVar> vars
    {
      get { return _vars; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncVar")]
  public partial class SyncVar : global::ProtoBuf.IExtensible
  {
    public SyncVar() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _param = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param
    {
      get { return _param; }
      set { _param = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipInfo")]
  public partial class EquipInfo : global::ProtoBuf.IExtensible
  {
    public EquipInfo() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _dataId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dataId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dataId
    {
      get { return _dataId; }
      set { _dataId = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EvacuateInfo")]
  public partial class EvacuateInfo : global::ProtoBuf.IExtensible
  {
    public EvacuateInfo() {}
    
    private string _playerGuid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerGuid
    {
      get { return _playerGuid; }
      set { _playerGuid = value; }
    }
    private SSIT.proto.PBVector3 _targetPos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.PBVector3 targetPos
    {
      get { return _targetPos; }
      set { _targetPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBVector3")]
  public partial class PBVector3 : global::ProtoBuf.IExtensible
  {
    public PBVector3() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBQuaternion")]
  public partial class PBQuaternion : global::ProtoBuf.IExtensible
  {
    public PBQuaternion() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _w = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float w
    {
      get { return _w; }
      set { _w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LobbyChatMessage")]
  public partial class LobbyChatMessage : global::ProtoBuf.IExtensible
  {
    public LobbyChatMessage() {}
    
    private string _Content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private string _FromGuid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"FromGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FromGuid
    {
      get { return _FromGuid; }
      set { _FromGuid = value; }
    }
    private SSIT.proto.EnMessageContentType _ContentType = SSIT.proto.EnMessageContentType.TEXT;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ContentType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SSIT.proto.EnMessageContentType.TEXT)]
    public SSIT.proto.EnMessageContentType ContentType
    {
      get { return _ContentType; }
      set { _ContentType = value; }
    }
    private SSIT.proto.VoiceData _Voice = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Voice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SSIT.proto.VoiceData Voice
    {
      get { return _Voice; }
      set { _Voice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VoiceData")]
  public partial class VoiceData : global::ProtoBuf.IExtensible
  {
    public VoiceData() {}
    
    private int _Frequency = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Frequency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Frequency
    {
      get { return _Frequency; }
      set { _Frequency = value; }
    }
    private int _Samples = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Samples", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Samples
    {
      get { return _Samples; }
      set { _Samples = value; }
    }
    private int _Length = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Length
    {
      get { return _Length; }
      set { _Length = value; }
    }
    private byte[] _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private int _Channel = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Channel
    {
      get { return _Channel; }
      set { _Channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnMessageType")]
    public enum EnMessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION", Value=0)]
      ACTION = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELF", Value=1)]
      SELF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=2)]
      OTHER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM", Value=3)]
      SYSTEM = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnWeather")]
    public enum EnWeather
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUN", Value=0)]
      SUN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAINY", Value=1)]
      RAINY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SNOWY", Value=2)]
      SNOWY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOG", Value=3)]
      FOG = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDY", Value=4)]
      WINDY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOUDY", Value=5)]
      CLOUDY = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnWindDirection")]
    public enum EnWindDirection
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOWIND", Value=0)]
      NOWIND = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORTH", Value=1)]
      NORTH = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORTHEAST", Value=2)]
      NORTHEAST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAST", Value=3)]
      EAST = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUTHEAST", Value=4)]
      SOUTHEAST = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUTH", Value=5)]
      SOUTH = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUTHWEST", Value=6)]
      SOUTHWEST = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEST", Value=7)]
      WEST = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORTHWEST", Value=8)]
      NORTHWEST = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnMessageContentType")]
    public enum EnMessageContentType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEXT", Value=0)]
      TEXT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VOICE", Value=1)]
      VOICE = 1
    }
  
}