// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: AccidentTableModel
	
  [System.Serializable]
	public partial class AccidentTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// Accident
		/// </summary>
		public List<AccidentDefine> Accident = new List<AccidentDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, AccidentDefine> _AccidentByAccidentID = new Dictionary<int, AccidentDefine>();
        public AccidentDefine GetAccidentByAccidentID(int AccidentID, AccidentDefine def = default(AccidentDefine))
        {
            AccidentDefine ret;
            if ( _AccidentByAccidentID.TryGetValue( AccidentID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(AccidentDefine) )
			{
				TableLogger.ErrorLine("GetAccidentByAccidentID failed, AccidentID: {0}", AccidentID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( AccidentTableModel ins)
		{
            			// Build Accident Index
			for( int i = 0;i< ins.Accident.Count;i++)
			{
				var element = ins.Accident[i];
				
				ins._AccidentByAccidentID.Add(element.AccidentID, element);
				
			}

        }
        
      public void DeserializeRe( AccidentTableModel ins)
		{
            			// Build Accident Index
			for( int i = 0;i< ins.Accident.Count;i++)
			{
				var element = ins.Accident[i];
				
				if(!_AccidentByAccidentID.ContainsKey(element.AccidentID))
				{
					this.Accident.Add(ins.Accident[i]);
					_AccidentByAccidentID.Add(element.AccidentID, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: Accident
	
  [System.Serializable]
	public partial class AccidentDefine
	{
	
		
		/// <summary> 
		/// 事故ID
		/// </summary>
		public int AccidentID = 0; 
		
		/// <summary> 
		/// 事件名称
		/// </summary>
		public string AccidentName = ""; 
		
		/// <summary> 
		/// 事件类型 1、火灾 2、泻露 3、伤员 4、普通障碍
		/// </summary>
		public string AccidentType = ""; 
		
		/// <summary> 
		/// 事故道具ID
		/// </summary>
		public int AccidentItemID = 0; 
	
	

	} 

}
