// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: BackgroundItemTableModel
	
  [System.Serializable]
	public partial class BackgroundItemTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// BackgroundItem
		/// </summary>
		public List<BackgroundItemDefine> BackgroundItem = new List<BackgroundItemDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, BackgroundItemDefine> _BackgroundItemByItemID = new Dictionary<int, BackgroundItemDefine>();
        public BackgroundItemDefine GetBackgroundItemByItemID(int ItemID, BackgroundItemDefine def = default(BackgroundItemDefine))
        {
            BackgroundItemDefine ret;
            if ( _BackgroundItemByItemID.TryGetValue( ItemID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(BackgroundItemDefine) )
			{
				TableLogger.ErrorLine("GetBackgroundItemByItemID failed, ItemID: {0}", ItemID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( BackgroundItemTableModel ins)
		{
            			// Build BackgroundItem Index
			for( int i = 0;i< ins.BackgroundItem.Count;i++)
			{
				var element = ins.BackgroundItem[i];
				
				ins._BackgroundItemByItemID.Add(element.ItemID, element);
				
			}

        }
        
      public void DeserializeRe( BackgroundItemTableModel ins)
		{
            			// Build BackgroundItem Index
			for( int i = 0;i< ins.BackgroundItem.Count;i++)
			{
				var element = ins.BackgroundItem[i];
				
				if(!_BackgroundItemByItemID.ContainsKey(element.ItemID))
				{
					this.BackgroundItem.Add(ins.BackgroundItem[i]);
					_BackgroundItemByItemID.Add(element.ItemID, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: BackgroundItem
	
  [System.Serializable]
	public partial class BackgroundItemDefine
	{
	
		
		/// <summary> 
		/// 物体ID
		/// </summary>
		public int ItemID = 0; 
		
		/// <summary> 
		/// 物体名称
		/// </summary>
		public string ItemName = ""; 
		
		/// <summary> 
		/// 物体类型
		/// </summary>
		public string ItemType = ""; 
		
		/// <summary> 
		/// 应急资源子类型 1.应急设备 2.报警设备 标签子类型 1.标签 触发器子类型 1.距离触发器
		/// </summary>
		public string ItemTypeSub = ""; 
		
		/// <summary> 
		/// 关联总表ItemTable的ID
		/// </summary>
		public int RelationID = 0; 
	
	

	} 

}
