// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: BackgroundSkillTableModel
	
  [System.Serializable]
	public partial class BackgroundSkillTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// BackgroundSkill
		/// </summary>
		public List<BackgroundSkillDefine> BackgroundSkill = new List<BackgroundSkillDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, BackgroundSkillDefine> _BackgroundSkillByid = new Dictionary<int, BackgroundSkillDefine>();
        public BackgroundSkillDefine GetBackgroundSkillById(int id, BackgroundSkillDefine def = default(BackgroundSkillDefine))
        {
            BackgroundSkillDefine ret;
            if ( _BackgroundSkillByid.TryGetValue( id, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(BackgroundSkillDefine) )
			{
				TableLogger.ErrorLine("GetBackgroundSkillByid failed, id: {0}", id);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( BackgroundSkillTableModel ins)
		{
            			// Build BackgroundSkill Index
			for( int i = 0;i< ins.BackgroundSkill.Count;i++)
			{
				var element = ins.BackgroundSkill[i];
				
				ins._BackgroundSkillByid.Add(element.id, element);
				
			}

        }
        
      public void DeserializeRe( BackgroundSkillTableModel ins)
		{
            			// Build BackgroundSkill Index
			for( int i = 0;i< ins.BackgroundSkill.Count;i++)
			{
				var element = ins.BackgroundSkill[i];
				
				if(!_BackgroundSkillByid.ContainsKey(element.id))
				{
					this.BackgroundSkill.Add(ins.BackgroundSkill[i]);
					_BackgroundSkillByid.Add(element.id, element);
				}
				
			}

        }
	} 

	// Defined in table: BackgroundSkill
	
  [System.Serializable]
	public partial class BackgroundSkillDefine
	{
	
		/// <summary> 
		/// 物体ID
		/// </summary>
		public int id = 0; 
		
		/// <summary> 
		/// 物体名称
		/// </summary>
		public string skillName = ""; 
		
		/// <summary> 
		/// 应急措施类型
		/// </summary>
		public string skillType = ""; 
		
		/// <summary> 
		/// 关联总表ItemTable的ID
		/// </summary>
		public int relationID = 0; 
	
	

	} 

}
