// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: CompanyTableModel
	
  [System.Serializable]
	public partial class CompanyTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// Company
		/// </summary>
		public List<CompanyDefine> Company = new List<CompanyDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, CompanyDefine> _CompanyByCompanyID = new Dictionary<int, CompanyDefine>();
        public CompanyDefine GetCompanyByCompanyID(int CompanyID, CompanyDefine def = default(CompanyDefine))
        {
            CompanyDefine ret;
            if ( _CompanyByCompanyID.TryGetValue( CompanyID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(CompanyDefine) )
			{
				TableLogger.ErrorLine("GetCompanyByCompanyID failed, CompanyID: {0}", CompanyID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( CompanyTableModel ins)
		{
            			// Build Company Index
			for( int i = 0;i< ins.Company.Count;i++)
			{
				var element = ins.Company[i];
				
				ins._CompanyByCompanyID.Add(element.CompanyID, element);
				
			}

        }
        
      public void DeserializeRe( CompanyTableModel ins)
		{
            			// Build Company Index
			for( int i = 0;i< ins.Company.Count;i++)
			{
				var element = ins.Company[i];
				
				if(!_CompanyByCompanyID.ContainsKey(element.CompanyID))
				{
					this.Company.Add(ins.Company[i]);
					_CompanyByCompanyID.Add(element.CompanyID, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: Company
	
  [System.Serializable]
	public partial class CompanyDefine
	{
	
		
		/// <summary> 
		/// 企业ID
		/// </summary>
		public int CompanyID = 0; 
		
		/// <summary> 
		/// 企业名称
		/// </summary>
		public string CompanyName = ""; 
		
		/// <summary> 
		/// 企业描述
		/// </summary>
		public string CompanyDesc = ""; 
		
		/// <summary> 
		/// 企业标识符
		/// </summary>
		public string CompanyIdentifier = ""; 
		
		/// <summary> 
		/// 前台登录背景
		/// </summary>
		public string LoginBgPath = ""; 
		
		/// <summary> 
		/// 前台大厅背景
		/// </summary>
		public string LobbyBgPath = ""; 
		
		/// <summary> 
		/// 后台事故设定背景
		/// </summary>
		public string SettingFormBgPath = ""; 
	
	

	} 

}
