// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: DeviceTableModel
	
  [System.Serializable]
	public partial class DeviceTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// Device
		/// </summary>
		public List<DeviceDefine> Device = new List<DeviceDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, DeviceDefine> _DeviceByItemID = new Dictionary<int, DeviceDefine>();
        public DeviceDefine GetDeviceByItemID(int ItemID, DeviceDefine def = default(DeviceDefine))
        {
            DeviceDefine ret;
            if ( _DeviceByItemID.TryGetValue( ItemID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(DeviceDefine) )
			{
				TableLogger.ErrorLine("GetDeviceByItemID failed, ItemID: {0}", ItemID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( DeviceTableModel ins)
		{
            			// Build Device Index
			for( int i = 0;i< ins.Device.Count;i++)
			{
				var element = ins.Device[i];
				
				ins._DeviceByItemID.Add(element.ItemID, element);
				
			}

        }
        
      public void DeserializeRe( DeviceTableModel ins)
		{
            			// Build Device Index
			for( int i = 0;i< ins.Device.Count;i++)
			{
				var element = ins.Device[i];
				
				if(!_DeviceByItemID.ContainsKey(element.ItemID))
				{
					this.Device.Add(ins.Device[i]);
					_DeviceByItemID.Add(element.ItemID, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: Device
	
  [System.Serializable]
	public partial class DeviceDefine
	{
	
		
		/// <summary> 
		/// 设备ID
		/// </summary>
		public int ItemID = 0; 
		
		/// <summary> 
		/// 设备位号（三维场景中）
		/// </summary>
		public string BitNumber = ""; 
		
		/// <summary> 
		/// 设备名称
		/// </summary>
		public string DisplayName = ""; 
		
		/// <summary> 
		/// 设备类型
		/// </summary>
		public string Type = ""; 
		
		
		public string Icon = ""; 
		
		/// <summary> 
		/// 描述
		/// </summary>
		public string Description = ""; 
		
		/// <summary> 
		/// 详细介绍
		/// </summary>
		public string Parameter = ""; 
		
		/// <summary> 
		/// 视角
		/// </summary>
		public string Viewport = ""; 
		
		/// <summary> 
		/// 场景id
		/// </summary>
		public int SceneId = 0; 
		
		/// <summary> 
		/// 备注
		/// </summary>
		public string Remark = ""; 
	
	

	} 

}
