// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: EmergencyPowerTableModel
	
  [System.Serializable]
	public partial class EmergencyPowerTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// EmergencyPower
		/// </summary>
		public List<EmergencyPowerDefine> EmergencyPower = new List<EmergencyPowerDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, EmergencyPowerDefine> _EmergencyPowerByid = new Dictionary<int, EmergencyPowerDefine>();
        public EmergencyPowerDefine GetEmergencyPowerById(int id, EmergencyPowerDefine def = default(EmergencyPowerDefine))
        {
            EmergencyPowerDefine ret;
            if ( _EmergencyPowerByid.TryGetValue( id, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(EmergencyPowerDefine) )
			{
				TableLogger.ErrorLine("GetEmergencyPowerByid failed, id: {0}", id);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( EmergencyPowerTableModel ins)
		{
            			// Build EmergencyPower Index
			for( int i = 0;i< ins.EmergencyPower.Count;i++)
			{
				var element = ins.EmergencyPower[i];
				
				ins._EmergencyPowerByid.Add(element.id, element);
				
			}

        }
        
      public void DeserializeRe( EmergencyPowerTableModel ins)
		{
            			// Build EmergencyPower Index
			for( int i = 0;i< ins.EmergencyPower.Count;i++)
			{
				var element = ins.EmergencyPower[i];
				
				if(!_EmergencyPowerByid.ContainsKey(element.id))
				{
					this.EmergencyPower.Add(ins.EmergencyPower[i]);
					_EmergencyPowerByid.Add(element.id, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: EmergencyPower
	
  [System.Serializable]
	public partial class EmergencyPowerDefine
	{
	
		
		/// <summary> 
		/// 模型ID
		/// </summary>
		public int id = 0; 
		
		/// <summary> 
		/// 模型名称
		/// </summary>
		public string ModelName = ""; 
		
		/// <summary> 
		/// 模型类型 1、值班人员 2、支援力量 3、无关人员
		/// </summary>
		public string ModelType = ""; 
		
		
		public int ModelTypeID = 0; 
		
		/// <summary> 
		/// 模型道具ID
		/// </summary>
		public int ModelItemID = 0; 
	
	

	} 

}
