// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: ForceUintTableModel
	
  [System.Serializable]
	public partial class ForceUintTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// ForceUint
		/// </summary>
		public List<ForceUintDefine> ForceUint = new List<ForceUintDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, ForceUintDefine> _ForceUintByID = new Dictionary<int, ForceUintDefine>();
        public ForceUintDefine GetForceUintByID(int ID, ForceUintDefine def = default(ForceUintDefine))
        {
            ForceUintDefine ret;
            if ( _ForceUintByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(ForceUintDefine) )
			{
				TableLogger.ErrorLine("GetForceUintByID failed, ID: {0}", ID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( ForceUintTableModel ins)
		{
            			// Build ForceUint Index
			for( int i = 0;i< ins.ForceUint.Count;i++)
			{
				var element = ins.ForceUint[i];
				
				ins._ForceUintByID.Add(element.ID, element);
				
			}

        }
        
      public void DeserializeRe( ForceUintTableModel ins)
		{
            			// Build ForceUint Index
			for( int i = 0;i< ins.ForceUint.Count;i++)
			{
				var element = ins.ForceUint[i];
				
				if(!_ForceUintByID.ContainsKey(element.ID))
				{
					this.ForceUint.Add(ins.ForceUint[i]);
					_ForceUintByID.Add(element.ID, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: ForceUint
	
  [System.Serializable]
	public partial class ForceUintDefine
	{
	
		
		/// <summary> 
		/// id 50000+（用于代码判断）
		/// </summary>
		public int ID = 0; 
		
		/// <summary> 
		/// 映射itemBase的ID
		/// </summary>
		public int MapId = 0; 
		
		/// <summary> 
		/// 名称
		/// </summary>
		public string Name = ""; 
		
		/// <summary> 
		/// 描述
		/// </summary>
		public string Desc = ""; 
		
		/// <summary> 
		/// 道具图标Id
		/// </summary>
		public int IconId = 0; 
		
		/// <summary> 
		/// 部门
		/// </summary>
		public string Profession = ""; 
		
		/// <summary> 
		/// 嵌入成员数量
		/// </summary>
		public int PlayerCount = 0; 
		
		
		public List<int> PlayerList = new List<int>(); 
		
		/// <summary> 
		/// 附属技能列表
		/// </summary>
		public List<int> AttachedSkillList = new List<int>(); 
		
		/// <summary> 
		/// 附属道具列表
		/// </summary>
		public List<int> AttachedItemList = new List<int>(); 
	
	

	} 

}
