// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	// Defined in table: GlobalValue
	public enum EnGlobalValue
	{
		
		
		None = 0, 
		
		/// <summary> 
		/// 组织机构图标
		/// </summary>
		Org_Icon = 1000, 
		
		/// <summary> 
		/// 用户图标
		/// </summary>
		User_Icon = 1001, 
		
		/// <summary> 
		/// 场景图标
		/// </summary>
		Scene_Icon = 1002, 
		
		/// <summary> 
		/// 场景配置文件
		/// </summary>
		Scene_Config = 1003, 
		
		/// <summary> 
		/// 预案图标
		/// </summary>
		Scheme_Icon = 1004, 
		
		/// <summary> 
		/// 预案配置文件
		/// </summary>
		Scheme_Config = 1005, 
		
		/// <summary> 
		/// 任务步骤配置文件
		/// </summary>
		Task_Config = 1006, 
	
	}
	
	

	// Defined in table: GlobalValueTableModel
	
  [System.Serializable]
	public partial class GlobalValueTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// GlobalValue
		/// </summary>
		public List<GlobalValueDefine> GlobalValue = new List<GlobalValueDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, GlobalValueDefine> _GlobalValueByindex = new Dictionary<int, GlobalValueDefine>();
        public GlobalValueDefine GetGlobalValueByIndex(int index, GlobalValueDefine def = default(GlobalValueDefine))
        {
            GlobalValueDefine ret;
            if ( _GlobalValueByindex.TryGetValue( index, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(GlobalValueDefine) )
			{
				TableLogger.ErrorLine("GetGlobalValueByindex failed, index: {0}", index);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( GlobalValueTableModel ins)
		{
            			// Build GlobalValue Index
			for( int i = 0;i< ins.GlobalValue.Count;i++)
			{
				var element = ins.GlobalValue[i];
				
				ins._GlobalValueByindex.Add(element.index, element);
				
			}

        }
        
      public void DeserializeRe( GlobalValueTableModel ins)
		{
            			// Build GlobalValue Index
			for( int i = 0;i< ins.GlobalValue.Count;i++)
			{
				var element = ins.GlobalValue[i];
				
				if(!_GlobalValueByindex.ContainsKey(element.index))
				{
					this.GlobalValue.Add(ins.GlobalValue[i]);
					_GlobalValueByindex.Add(element.index, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: GlobalValue
	
  [System.Serializable]
	public partial class GlobalValueDefine
	{
	
		
		/// <summary> 
		/// 索引
		/// </summary>
		public int index = 0; 
		
		/// <summary> 
		/// 文本数据
		/// </summary>
		public string content = ""; 
	
	

	} 

}
