// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: MediumTableModel
	
  [System.Serializable]
	public partial class MediumTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// Medium
		/// </summary>
		public List<MediumDefine> Medium = new List<MediumDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, MediumDefine> _MediumByEquipID = new Dictionary<int, MediumDefine>();
        public MediumDefine GetMediumByEquipID(int EquipID, MediumDefine def = default(MediumDefine))
        {
            MediumDefine ret;
            if ( _MediumByEquipID.TryGetValue( EquipID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(MediumDefine) )
			{
				TableLogger.ErrorLine("GetMediumByEquipID failed, EquipID: {0}", EquipID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( MediumTableModel ins)
		{
            			// Build Medium Index
			for( int i = 0;i< ins.Medium.Count;i++)
			{
				var element = ins.Medium[i];
				
				ins._MediumByEquipID.Add(element.EquipID, element);
				
			}

        }
        
      public void DeserializeRe( MediumTableModel ins)
		{
            			// Build Medium Index
			for( int i = 0;i< ins.Medium.Count;i++)
			{
				var element = ins.Medium[i];
				
				if(!_MediumByEquipID.ContainsKey(element.EquipID))
				{
					this.Medium.Add(ins.Medium[i]);
					_MediumByEquipID.Add(element.EquipID, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: Medium
	
  [System.Serializable]
	public partial class MonitoringType
	{
	
		
		/// <summary> 
		/// 显示名称
		/// </summary>
		public string Name = ""; 
		
		/// <summary> 
		/// 单位
		/// </summary>
		public string Unit = ""; 
		
		/// <summary> 
		/// 死亡临界点
		/// </summary>
		public float CP = 0f; 
		
		/// <summary> 
		/// 警告临界点
		/// </summary>
		public float WP = 0f; 
		
		/// <summary> 
		/// 上限
		/// </summary>
		public float UL = 0f; 
		
		/// <summary> 
		/// 下限
		/// </summary>
		public float DL = 0f; 
		
		/// <summary> 
		/// 正常
		/// </summary>
		public float NO = 0f; 
		
		/// <summary> 
		/// 缩放因子
		/// </summary>
		public float FA = 0f; 
	
	

	} 

	// Defined in table: Medium
	
  [System.Serializable]
	public partial class MediumDefine
	{
	
		
		/// <summary> 
		/// 检测设备ID
		/// </summary>
		public int EquipID = 0; 
		
		/// <summary> 
		/// 设备位号（三维场景中）
		/// </summary>
		public string Name = ""; 
		
		/// <summary> 
		/// 检测范围
		/// </summary>
		public int QtArea = 0; 
		
		/// <summary> 
		/// 监测类型
		/// </summary>
		public List<MonitoringType> MonitoringItems = new List<MonitoringType>(); 
	
	

	} 

}
