// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: ProtectionsTableModel
	
  [System.Serializable]
	public partial class ProtectionsTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// Protections
		/// </summary>
		public List<ProtectionsDefine> Protections = new List<ProtectionsDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, ProtectionsDefine> _ProtectionsByProtectionsBaseID = new Dictionary<int, ProtectionsDefine>();
        public ProtectionsDefine GetProtectionsByProtectionsBaseID(int ProtectionsBaseID, ProtectionsDefine def = default(ProtectionsDefine))
        {
            ProtectionsDefine ret;
            if ( _ProtectionsByProtectionsBaseID.TryGetValue( ProtectionsBaseID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(ProtectionsDefine) )
			{
				TableLogger.ErrorLine("GetProtectionsByProtectionsBaseID failed, ProtectionsBaseID: {0}", ProtectionsBaseID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( ProtectionsTableModel ins)
		{
            			// Build Protections Index
			for( int i = 0;i< ins.Protections.Count;i++)
			{
				var element = ins.Protections[i];
				
				ins._ProtectionsByProtectionsBaseID.Add(element.ProtectionsBaseID, element);
				
			}

        }
        
      public void DeserializeRe( ProtectionsTableModel ins)
		{
            			// Build Protections Index
			for( int i = 0;i< ins.Protections.Count;i++)
			{
				var element = ins.Protections[i];
				
				if(!_ProtectionsByProtectionsBaseID.ContainsKey(element.ProtectionsBaseID))
				{
					this.Protections.Add(ins.Protections[i]);
					_ProtectionsByProtectionsBaseID.Add(element.ProtectionsBaseID, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: Protections
	
  [System.Serializable]
	public partial class ProtectionsDefine
	{
	
		
		/// <summary> 
		/// 防护类型ID
		/// </summary>
		public int ProtectionsBaseID = 0; 
		
		/// <summary> 
		/// 防护类型名称
		/// </summary>
		public string ProtectionsBaseName = ""; 
		
		/// <summary> 
		/// 所包含防护用具
		/// </summary>
		public List<int> ProtectionsList = new List<int>(); 
	
	

	} 

}
