// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: ResourcesTableModel
	
  [System.Serializable]
	public partial class ResourcesTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// Resources
		/// </summary>
		public List<ResourcesDefine> Resources = new List<ResourcesDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, ResourcesDefine> _ResourcesByid = new Dictionary<int, ResourcesDefine>();
        public ResourcesDefine GetResourcesById(int id, ResourcesDefine def = default(ResourcesDefine))
        {
            ResourcesDefine ret;
            if ( _ResourcesByid.TryGetValue( id, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(ResourcesDefine) )
			{
				TableLogger.ErrorLine("GetResourcesByid failed, id: {0}", id);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( ResourcesTableModel ins)
		{
            			// Build Resources Index
			for( int i = 0;i< ins.Resources.Count;i++)
			{
				var element = ins.Resources[i];
				
				ins._ResourcesByid.Add(element.id, element);
				
			}

        }
        
      public void DeserializeRe( ResourcesTableModel ins)
		{
            			// Build Resources Index
			for( int i = 0;i< ins.Resources.Count;i++)
			{
				var element = ins.Resources[i];
				
				if(!_ResourcesByid.ContainsKey(element.id))
				{
					this.Resources.Add(ins.Resources[i]);
					_ResourcesByid.Add(element.id, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: Resources
	
  [System.Serializable]
	public partial class ResourcesDefine
	{
	
		
		/// <summary> 
		/// ID
		/// </summary>
		public int id = 0; 
		
		/// <summary> 
		/// 名字
		/// </summary>
		public string name = ""; 
		
		/// <summary> 
		/// 描述
		/// </summary>
		public string desc = ""; 
		
		/// <summary> 
		/// 类型
		/// </summary>
		public int type = 0; 
		
		/// <summary> 
		/// 路径
		/// </summary>
		public string resourcePath = ""; 
		
		
		public string bundleId = ""; 
		
		
		public string resName = ""; 
	
	

	} 

}
