// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: SceneTableModel
	
  [System.Serializable]
	public partial class SceneTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// Scene
		/// </summary>
		public List<SceneDefine> Scene = new List<SceneDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, SceneDefine> _SceneBySceneID = new Dictionary<int, SceneDefine>();
        public SceneDefine GetSceneBySceneID(int SceneID, SceneDefine def = default(SceneDefine))
        {
            SceneDefine ret;
            if ( _SceneBySceneID.TryGetValue( SceneID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(SceneDefine) )
			{
				TableLogger.ErrorLine("GetSceneBySceneID failed, SceneID: {0}", SceneID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( SceneTableModel ins)
		{
            			// Build Scene Index
			for( int i = 0;i< ins.Scene.Count;i++)
			{
				var element = ins.Scene[i];
				
				ins._SceneBySceneID.Add(element.SceneID, element);
				
			}

        }
        
      public void DeserializeRe( SceneTableModel ins)
		{
            			// Build Scene Index
			for( int i = 0;i< ins.Scene.Count;i++)
			{
				var element = ins.Scene[i];
				
				if(!_SceneBySceneID.ContainsKey(element.SceneID))
				{
					this.Scene.Add(ins.Scene[i]);
					_SceneBySceneID.Add(element.SceneID, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: Scene
	
  [System.Serializable]
	public partial class SceneDefine
	{
	
		
		/// <summary> 
		/// 场景ID
		/// </summary>
		public int SceneID = 0; 
		
		/// <summary> 
		/// 场景显示名称
		/// </summary>
		public string SceneName = ""; 
		
		/// <summary> 
		/// 场景描述
		/// </summary>
		public string SceneDesc = ""; 
		
		/// <summary> 
		/// 场景2D图标
		/// </summary>
		public string SceneIconPath = ""; 
		
		/// <summary> 
		/// Unity场景名称
		/// </summary>
		public string SceneFileName = ""; 
		
		
		public List<int> SceneGroupList = new List<int>(); 
		
		
		public string MiniMapTexturePath = ""; 
		
		/// <summary> 
		/// 小地图UI位置
		/// </summary>
		public string MiniMapPos = ""; 
		
		/// <summary> 
		/// 小地图UI尺寸
		/// </summary>
		public string MiniMapRect = ""; 
		
		/// <summary> 
		/// 场景起始坐标
		/// </summary>
		public string MiniMapStartPos = ""; 
		
		/// <summary> 
		/// 场景终点坐标
		/// </summary>
		public string MiniMapEndPos = ""; 
	
	

	} 

}
