// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Table
{
	
	

	// Defined in table: TextureTableModel
	
  [System.Serializable]
	public partial class TextureTableModel
	{
	
		public Tabtoy.Logger TableLogger = Tabtoy.Logger.Instance();
	
		
		/// <summary> 
		/// Texture
		/// </summary>
		public List<TextureDefine> Texture = new List<TextureDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, TextureDefine> _TextureByid = new Dictionary<int, TextureDefine>();
        public TextureDefine GetTextureById(int id, TextureDefine def = default(TextureDefine))
        {
            TextureDefine ret;
            if ( _TextureByid.TryGetValue( id, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(TextureDefine) )
			{
				TableLogger.ErrorLine("GetTextureByid failed, id: {0}", id);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
      public static void Deserialize( TextureTableModel ins)
		{
            			// Build Texture Index
			for( int i = 0;i< ins.Texture.Count;i++)
			{
				var element = ins.Texture[i];
				
				ins._TextureByid.Add(element.id, element);
				
			}

        }
        
      public void DeserializeRe( TextureTableModel ins)
		{
            			// Build Texture Index
			for( int i = 0;i< ins.Texture.Count;i++)
			{
				var element = ins.Texture[i];
				
				if(!_TextureByid.ContainsKey(element.id))
				{
					this.Texture.Add(ins.Texture[i]);
					_TextureByid.Add(element.id, element);
				}
				
			}

        }
        
	

	} 

	// Defined in table: Texture
	
  [System.Serializable]
	public partial class TextureDefine
	{
	
		
		/// <summary> 
		/// 索引
		/// </summary>
		public int id = 0; 
		
		/// <summary> 
		/// 关联资源id
		/// </summary>
		public int resourceId = 0; 
		
		/// <summary> 
		/// 1.精灵(Sprite) 2.纹理(Texture) 3.图标(icon) 4.鼠标指针(Cursor)
		/// </summary>
		public int type = 0; 
		
		/// <summary> 
		/// 图集Id
		/// </summary>
		public int atlasId = 0; 
	
	

	} 

}
